ignored:
  # disable explicit version for apt install
  - DL3008
  # disable explicit version for apk install
  - DL3018
  # disable check for consecutive `RUN` instructions
  - DL3059
trustedRegistries:
  - docker.io
  - ghcr.io
  - quay.io
